### ISSUE TITLE
OVERVIEW | Syria - Economic Monitor

### ISSUE THREAD

**Issue by Holly-Transport** [datapartnership/syria-economic-monitor#67]
### Client Contact Email(s)

lzhao1@worldbank.org 

### Project Charge Code

IO 2022978 

### Project Manager

Holly Krambeck

### Project Sharepoint URL

https://worldbankgroup.sharepoint.com.mcas.ms/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FDevelopmentDataPartnershipCommunity%2DWBGroup%2FShared%20Documents%2FProjects%2FData%20Lab%2FSyria%20Economic%20Monitor&p=true&ga=1

### Project Web Book URL

http://datapartnership.org/syria-economic-monitor/

### Project Assignment (FY25)

[FY25 Syria Work Plan - December Issue](https://worldbankgroup.sharepoint.com/:w:/t/DevelopmentDataPartnershipCommunity-WBGroup/EYl-9DvKqLBEitTcwZXSq-cBoFLTbx5yMY2jWu3iq9gxxw?e=NkHTB5)

- [ ] NTL Update
- [ ] NTL New Analytics
- [ ] Conflict Trends Update
- [ ] Conflict New Analytics
- [ ] Maritime Trends Update
- [ ] Air Pollution Analytics
- [ ] Tree Cover Loss Update
- [ ] Tree Cover Loss New Analytics
- [ ] Vegetation Monitoring Update
- [ ] Vegetation New Analytics

### Project Assignment (FY24)

[FY24 Syria Work Plan.docx](https://github.com/user-attachments/files/16898394/FY24.Syria.Work.Plan.docx)

Challenge
The Syria Economic Monitor is a semi-annual economic publication of the World Bank, which provides updates on key economic developments, outlook, risks, and policies.

The conflict in Syria has inflicted a devastating impact on the inhabitants and economy, but measuring the true extent of the damage has been challenging. With the prolonged conflict, the country’s statistical capacity has been weakened, and reliable and timely information regarding many areas of economic activity, particularly trade, is inaccessible. Further, the Bank has no formal communication with the Syrian government, making basic data access and verification unusually challenging.

Solution
The Syria Economic Monitor team requested the WB Data Lab to explore use of alternative data to better understand changing trends in trade and economic activity, focusing on: port activity, surface cross-border transport routes, changes in observed agricultural production, observed nighttime lights, and reported conflict. The team, comprised of colleagues from the Global Operations Support Team (GOST), the Development Impact Monitoring and Evaluation team (DIME), the Development Data Partnership, and the WB Data Lab, worked with the Syria Economic Monitor team to explore use of alternative open and proprietary data sources to generate new data products that can be sustainably updated. With the datasets and methods provided, over time, the Syria team should be able to create a clearer picture of the state of the Syrian economy.

Results
Datasets and methods used to generate insights for this project have been prepared as Data Goods. Data Goods are comprised of data, reproducible methods (code), documentation, and sample insights. Unlike a traditional data analysis, which results in a single-use report or visualization, Data Goods are designed to be re-used for future updates and projects, thereby building the capacity of the World Bank and partner organizations to quickly and effectively deliver complex data science solutions to pressing global challenges.

```[tasklist]
### Tasks
```

**Comment by Holly-Transport** [comment]
@SahitiSarva @dmatekenya I propose, if she accepts, adding Isha to the remainder of the Syria 'land' tasks -- agriculture, tree cover loss, and environment.

**Comment by SahitiSarva** [comment]
The 15th October call went over an hour and we need to set up another call to discuss next steps.

**Comment by SahitiSarva** [comment]
Notes from the 11th November call - 
- Plot ACLED data on a map and show the conflict events that happen in the Lebanon-Syria border crossing
- Land border crossing and ports areas
- Send aviation trends between Lebanon and Syria

**Comment by SahitiSarva** [comment]
This project will be on hold for some time given the government in Syria was overthrown. Luan mentioned it on a call recentlly. The call was with researchers who used NTL in interesting other contexts that include smuggling and vulnerability analysis.

**Comment by SahitiSarva** [comment]
Notes from the 20th January call with Jose Manuel, Luan and Harun -- 

- They want to include Damage Assessments for multiple MENA countries - Gaza, West Bank, Libya, Syria, Lebanon, Yemen. 
- Yemn, Libya, Syria -- have a huge desert territory so the built up surface is smaller. 
- WHat % of the country's capital stock has been destroyed by the conflict. They dotn need classification of infrastructure. 
- Jose Manuel: Country wide analysis will require some time. Gaza will be the fastest because it already exists. 
- Timeline: 1 month
- They want to start with Gaza and Lebanon (start is October 2023).
- Gaza will likely be done within a week. 
- Syria microsoft building footprints date has been collected from 2014

- They want to get ACLED data over the last 10 years and narrow down the analysis only to those areas. However, this will depend on how much of the country is impacted by the conflict.
